
export const SET_LOADING = 'SET_LOADING';
export const SHOW_TOAST = 'SHOW_TOAST';

export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_FETCH_USER = 'AUTH_FETCH_USER';

export const OPEN_CONTACTS_MODAL = 'OPEN_CONTACTS_MODAL';
export const CLOSE_CONTACTS_MODAL = 'CLOSE_CONTACTS_MODAL';
export const FETCH_CONTACTS = 'FETCH_CONTACTS';

export const FETCH_CHATS = 'FETCH_CHATS';
export const CREATE_CHATS = 'CREATE_CHAT';
export const DELETE_CHAT = 'DELETE_CHAT';

export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const SEND_MESSAGE = 'SEND_MESSAGE';
